version: "3.8"

services:
  nginxserver:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/nginx.conf:ro

  php:
  mysql:
  composer:
  artisian:
  npm:

