version: "3.8"

services:
  nginxserver:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/nginx.conf:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
  composer:
  artisian:
  npm:

